services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 12000:3000
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    command: sh -c "npm start"
  db:
    image: mongo:latest
    ports:
      - 27017:27017
  backend:
    build:
      context: ./backend
    ports:
      - 13000:4000
    links:
      - db
    volumes:
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules
    command: sh -c "npm start"
volumes:
  node_modules: