services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
  app:
    build:
      context: .
    ports:
      - 13000:4000
    links:
      - db
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm start"
volumes:
  node_modules: